/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
/*
 *
 * */

#include "stdint.h"

#define RCC_BASE   0x40021000
#define GPIOA_BASE 0x40010800

#define RCC_APB2ENR    *((volatile uint32_t *) (RCC_BASE + 0x18))
#define GPIOA_CHR    *((volatile uint32_t *) (GPIOA_BASE + 0x04))
#define GPIOA_ODR    *((volatile uint32_t *) (GPIOA_BASE + 0x0c))
 typedef union {
	uint32_t PORTA;
	struct {
		uint32_t PA0:1;
		uint32_t PA1:1;
		uint32_t PA2:1;
		uint32_t PA3:1;
		uint32_t PA4:1;
		uint32_t PA5:1;
		uint32_t PA6:1;
		uint32_t PA7:1;
		uint32_t PA8:1;
		uint32_t PA9:1;
		uint32_t PA10:1;
		uint32_t PA11:1;
		uint32_t PA12:1;
		uint32_t PA13:1;
		uint32_t PA14:1;
		uint32_t PA15:1;
		uint32_t PA16:1;
		uint32_t PA17:1;
		uint32_t PA18:1;
		uint32_t PA19:1;
		uint32_t PA20:1;
		uint32_t PA21:1;
		uint32_t PA22:1;
		uint32_t PA23:1;
		uint32_t PA24:1;
		uint32_t PA25:1;
		uint32_t PA26:1;
		uint32_t PA27:1;
		uint32_t PA28:1;
		uint32_t PA29:1;
		uint32_t PA30:1;
		uint32_t PA31:1;

	}PORTA_Pins;
}R_GPIOA_ODR;

int main(void)
{
	RCC_APB2ENR |= 1<<2;
	GPIOA_CHR &= 0xff0fffff;
	GPIOA_CHR |= 0x00200000;
	volatile R_GPIOA_ODR * PA=(volatile R_GPIOA_ODR *) (GPIOA_BASE + 0x0c);
	while(1)
	{
	PA->PORTA_Pins.PA13=1;
	for(int i=0;i<5000;i++);
	PA->PORTA_Pins.PA13=0;
	for(int i=0;i<5000;i++);

}
}
